- name: Execute script to clear memory
  hosts: client  # Replace with the target hosts where you want to clear memory
  become: true

  tasks:
    - name: Print current memory usage before clearing cache
      shell: free -h
      register: memory_before

    - debug:
        var: memory_before.stdout_lines

    - name: Copy the script to the remote host
      copy:
        src: https://github.com/premkumargunasekar/Ansible.git
        dest: https://github.com/premkumargunasekar/Ansible.git/to/tmp/clear_memory.sh
        mode: '0755'  # Make sure the script is executable

    - name: Execute the script
      shell: https://github.com/premkumargunasekar/Ansible.git/to/tmp/clear_memory.sh

    - name: Print current memory usage after clearing cache
      shell: free -h
      register: memory_after

    - debug:
        var: memory_after.stdout_lines

  handlers:
    - name: Save output to log file
      copy:
        content: |
          Pre-execution memory usage:
          {{ memory_before.stdout | join('\n') }}

          Post-execution memory usage:
          {{ memory_after.stdout | join('\n') }}
        dest: /tmp/memory_clearing_log.txt
      listen: post_execution

    - name: Print log file location
      debug:
        msg: "Log file stored at /tmp/memory_clearing_log.txt"
      listen: post_execution
      run_once: yes  # Ensure this task runs only once on the control machine

    - meta: flush_handlers
